-- =========================================================================
-- HỆ THỐNG CƠ SỞ DỮ LIỆU ĐÁNH GIÁ KPI - BAN TỔ CHỨC TỈNH ỦY ĐẮK LẮK
-- Căn cứ pháp lý: Quy định số 01-QĐ/BTCTU ngày 28/11/2025
-- Phiên bản: Enterprise CSDL v2.0 (Chuẩn hóa Schema, Ràng buộc, Soft-Delete & Analytics Views)
-- =========================================================================

-- 1. Phòng chuyên môn (Departments)
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Vị trí việc làm (Positions)
CREATE TABLE IF NOT EXISTS positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    job_description TEXT
);

-- 3. Cán bộ, công chức (Users)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(150),
    phone VARCHAR(20),
    department_id BIGINT,
    position_id BIGINT,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_dept FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    CONSTRAINT fk_user_pos FOREIGN KEY (position_id) REFERENCES positions(id) ON DELETE SET NULL,
    CONSTRAINT chk_user_role CHECK (role IN ('ADMIN', 'LANH_DAO_BAN', 'TRUONG_PHONG', 'CHUYEN_VIEN')),
    CONSTRAINT chk_user_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);

-- 4. Bộ tiêu chí định lượng KPI (KpiCriteria)
CREATE TABLE IF NOT EXISTS kpi_criteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    group_type VARCHAR(10) NOT NULL,
    max_score DOUBLE NOT NULL,
    scoring_guide TEXT,
    target_role VARCHAR(50) DEFAULT 'ALL',
    CONSTRAINT chk_criteria_group CHECK (group_type IN ('A', 'B', 'C')),
    CONSTRAINT chk_criteria_max_score CHECK (max_score > 0 AND max_score <= 100)
);

-- 5. Bảng Nhiệm vụ công tác (Tasks) - Đầy đủ 4 loại hình công tác & Ràng buộc toàn vẹn
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    description TEXT,
    assigned_to BIGINT NOT NULL,
    assigned_by BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    criteria_id BIGINT,
    
    -- Phân loại nghiệp vụ theo Quy định số 01-QĐ/BTCTU
    task_type VARCHAR(50) DEFAULT 'VAN_BAN',
    complexity VARCHAR(30) DEFAULT 'TRUNG_BINH',
    
    -- Nghiệp vụ đặc thù
    speech_approved BOOLEAN DEFAULT FALSE,
    field_trip_location VARCHAR(255),
    field_trip_result TEXT,
    office_discipline_note TEXT,
    
    priority VARCHAR(20) DEFAULT 'NORMAL',
    start_date DATE NOT NULL,
    due_date DATE NOT NULL,
    completed_date DATE,
    progress INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'IN_PROGRESS',
    evidence_text TEXT,
    weight DOUBLE DEFAULT 1.0,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_assignee FOREIGN KEY (assigned_to) REFERENCES users(id),
    CONSTRAINT fk_task_assigner FOREIGN KEY (assigned_by) REFERENCES users(id),
    CONSTRAINT fk_task_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_task_criteria FOREIGN KEY (criteria_id) REFERENCES kpi_criteria(id),
    CONSTRAINT chk_task_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT chk_task_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE')),
    CONSTRAINT chk_task_type CHECK (task_type IN ('VAN_BAN', 'HOP', 'CONG_TAC', 'CONG_SO')),
    CONSTRAINT chk_task_complexity CHECK (complexity IN ('DE', 'TRUNG_BINH', 'KHO', 'DAC_BIET')),
    CONSTRAINT chk_task_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    CONSTRAINT chk_task_weight CHECK (weight > 0)
);

-- 6. Nhật ký công việc hằng ngày & Báo cáo tuần (WorkLogs)
CREATE TABLE IF NOT EXISTS work_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    task_id BIGINT,
    log_date DATE NOT NULL,
    week_number INT NOT NULL,
    month_val VARCHAR(20) NOT NULL,
    work_content TEXT NOT NULL,
    hours_spent DOUBLE DEFAULT 8.0,
    result_status VARCHAR(50),
    supervisor_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_log_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_log_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    CONSTRAINT chk_log_hours CHECK (hours_spent >= 0 AND hours_spent <= 24),
    CONSTRAINT chk_log_week CHECK (week_number BETWEEN 1 AND 53)
);

-- 7. Đánh giá Cán bộ cá nhân (Evaluations)
CREATE TABLE IF NOT EXISTS evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    period_type VARCHAR(20) NOT NULL,
    period_value VARCHAR(50) NOT NULL,
    self_score DOUBLE DEFAULT 0.0,
    manager_score DOUBLE DEFAULT 0.0,
    final_score DOUBLE DEFAULT 0.0,
    ranking VARCHAR(50),
    self_notes TEXT,
    manager_notes TEXT,
    leader_notes TEXT,
    status VARCHAR(30) DEFAULT 'DRAFT',
    evaluated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_by BIGINT,
    approved_at TIMESTAMP,
    CONSTRAINT fk_eval_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_eval_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_eval_approver FOREIGN KEY (approved_by) REFERENCES users(id),
    CONSTRAINT chk_eval_period_type CHECK (period_type IN ('MONTH', 'QUARTER', 'YEAR')),
    CONSTRAINT chk_eval_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'REVIEWED', 'APPROVED')),
    CONSTRAINT chk_eval_self_score CHECK (self_score BETWEEN 0 AND 100),
    CONSTRAINT chk_eval_manager_score CHECK (manager_score IS NULL OR manager_score BETWEEN 0 AND 100),
    CONSTRAINT chk_eval_final_score CHECK (final_score IS NULL OR final_score BETWEEN 0 AND 100)
);

-- 8. Ban Tổ chức đánh giá Phòng chuyên môn (DepartmentEvaluations)
-- Cột tính toán tự động GENERATED ALWAYS AS theo thang điểm Quy định 01-QĐ/BTCTU:
-- Tiến độ (30đ) + Chất lượng (30đ) + Chuyển đổi số (15đ) + Kỷ cương (15đ) + Chuyên viên (10đ) = 100đ
CREATE TABLE IF NOT EXISTS department_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    period_type VARCHAR(20) NOT NULL,
    period_value VARCHAR(50) NOT NULL,
    plan_score DOUBLE DEFAULT 0.0,
    quality_score DOUBLE DEFAULT 0.0,
    it_digital_score DOUBLE DEFAULT 0.0,
    discipline_score DOUBLE DEFAULT 0.0,
    avg_staff_score DOUBLE DEFAULT 0.0,
    total_score DOUBLE GENERATED ALWAYS AS (plan_score + quality_score + it_digital_score + discipline_score + avg_staff_score),
    ranking VARCHAR(50),
    leader_feedback TEXT,
    evaluated_by BIGINT,
    evaluated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dept_eval_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_dept_eval_leader FOREIGN KEY (evaluated_by) REFERENCES users(id),
    CONSTRAINT chk_dept_period_type CHECK (period_type IN ('MONTH', 'QUARTER', 'YEAR')),
    CONSTRAINT chk_dept_plan_score CHECK (plan_score BETWEEN 0 AND 30),
    CONSTRAINT chk_dept_quality_score CHECK (quality_score BETWEEN 0 AND 30),
    CONSTRAINT chk_dept_digital_score CHECK (it_digital_score BETWEEN 0 AND 15),
    CONSTRAINT chk_dept_discipline_score CHECK (discipline_score BETWEEN 0 AND 15),
    CONSTRAINT chk_dept_avg_staff_score CHECK (avg_staff_score BETWEEN 0 AND 10)
);

-- 9. Chi tiết chấm điểm từng tiêu chí (EvaluationDetails)
CREATE TABLE IF NOT EXISTS evaluation_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT NOT NULL,
    criteria_id BIGINT NOT NULL,
    self_points DOUBLE DEFAULT 0.0,
    manager_points DOUBLE DEFAULT 0.0,
    final_points DOUBLE DEFAULT 0.0,
    notes TEXT,
    CONSTRAINT fk_detail_eval FOREIGN KEY (evaluation_id) REFERENCES evaluations(id) ON DELETE CASCADE,
    CONSTRAINT fk_detail_crit FOREIGN KEY (criteria_id) REFERENCES kpi_criteria(id),
    CONSTRAINT chk_detail_self_points CHECK (self_points BETWEEN 0 AND 100),
    CONSTRAINT chk_detail_manager_points CHECK (manager_points IS NULL OR manager_points BETWEEN 0 AND 100),
    CONSTRAINT chk_detail_final_points CHECK (final_points IS NULL OR final_points BETWEEN 0 AND 100)
);

-- 10. Nhật ký kiểm toán an toàn dữ liệu (AuditLogs)
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(100),
    action VARCHAR(50) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id BIGINT,
    details TEXT,
    ip_address VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================================
-- HỆ THỐNG CHỈ MỤC TỐI ƯU TRUY VẤN (PERFORMANCE INDEXES)
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_dept ON users(department_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee_status ON tasks(assigned_to, status);
CREATE INDEX IF NOT EXISTS idx_tasks_dept_duedate ON tasks(department_id, due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_type ON tasks(task_type);
CREATE INDEX IF NOT EXISTS idx_worklogs_date ON work_logs(log_date);
CREATE INDEX IF NOT EXISTS idx_worklogs_week ON work_logs(week_number);
CREATE INDEX IF NOT EXISTS idx_eval_user_period ON evaluations(user_id, period_value);
CREATE INDEX IF NOT EXISTS idx_dept_eval_period ON department_evaluations(department_id, period_value);

-- =========================================================================
-- KHUNG NHÌN PHÂN TÍCH THÔNG MINH (ANALYTICS VIEWS)
-- =========================================================================
-- View 1: Cảnh báo nhiệm vụ quá hạn hoặc sắp đến hạn trong vòng 48h
CREATE OR REPLACE VIEW v_task_overdue_warning AS
SELECT 
    t.id AS task_id,
    t.title,
    t.task_type,
    t.priority,
    t.progress,
    t.status,
    t.due_date,
    u.full_name AS assignee_name,
    d.name AS department_name,
    DATEDIFF('DAY', CURRENT_DATE, t.due_date) AS days_remaining
FROM tasks t
JOIN users u ON t.assigned_to = u.id
JOIN departments d ON t.department_id = d.id
WHERE t.status != 'COMPLETED';

-- View 2: Tổng hợp hiệu suất KPI phòng ban
CREATE OR REPLACE VIEW v_department_kpi_summary AS
SELECT 
    d.id AS department_id,
    d.name AS department_name,
    COUNT(t.id) AS total_tasks,
    COUNT(CASE WHEN t.status = 'COMPLETED' THEN 1 END) AS completed_tasks,
    ROUND(AVG(CAST(t.progress AS DOUBLE)), 1) AS avg_progress
FROM departments d
LEFT JOIN tasks t ON d.id = t.department_id
GROUP BY d.id, d.name;

-- =========================================================================
-- DỮ LIỆU KHỞI TẠO BAN ĐẦU (SEED DATA - ĐẦY ĐỦ TỪNG CỘT)
-- =========================================================================
MERGE INTO departments (id, code, name, description) KEY(id) VALUES
(1, 'LANH_DAO', 'Lãnh đạo Ban Tổ chức Tỉnh ủy', 'Trưởng ban và các Phó Trưởng ban phụ trách chỉ đạo chung toàn diện'),
(2, 'TC_DANG', 'Phòng Tổ chức Đảng và Đảng viên', 'Tham mưu công tác xây dựng tổ chức cơ sở Đảng và quản lý hồ sơ CSDL Đảng viên'),
(3, 'CAN_BO', 'Phòng Cán bộ', 'Tham mưu công tác quy hoạch, điều động, bổ nhiệm, đào tạo và chính sách cán bộ'),
(4, 'BVCTNB', 'Phòng Bảo vệ Chính trị Nội bộ', 'Thẩm tra, xác minh và kết luận tiêu chuẩn chính trị phục vụ công tác cán bộ'),
(5, 'VAN_PHONG', 'Văn phòng Ban', 'Tổng hợp, văn thư lưu trữ, tài chính và ứng dụng Công nghệ Thông tin, chuyển đổi số');

MERGE INTO positions (id, code, title, job_description) KEY(id) VALUES
(1, 'TRUONG_BAN', 'Trưởng Ban Tổ chức Tỉnh ủy', 'Lãnh đạo, quản lý toàn diện các mặt công tác của Ban Tổ chức Tỉnh ủy'),
(2, 'PHO_TRUONG_BAN', 'Phó Trưởng Ban Tổ chức Tỉnh ủy', 'Giúp Trưởng ban phụ trách, chỉ đạo các mảng công tác được phân công'),
(3, 'TRUONG_PHONG', 'Trưởng phòng chuyên môn', 'Chịu trách nhiệm trước Lãnh đạo Ban về toàn bộ hoạt động của phòng'),
(4, 'CV_CNTT', 'Chuyên viên Công nghệ thông tin', 'Quản trị mạng LAN, an toàn thông tin, bảo mật CSDL Đảng viên và chuyển đổi số');

MERGE INTO users (id, username, password_hash, full_name, email, phone, department_id, position_id, role, status) KEY(id) VALUES
(1, 'admin', 'password123', 'Quản trị viên Hệ thống', 'admin@btctu.daklak.gov.vn', '0905111222', 5, 4, 'ADMIN', 'ACTIVE'),
(2, 'lanhdao', 'password123', 'Đồng chí Nguyễn Văn An (Trưởng Ban)', 'lanhdao@btctu.daklak.gov.vn', '0913444555', 1, 1, 'LANH_DAO_BAN', 'ACTIVE'),
(3, 'tp_canbo', 'password123', 'Đồng chí Trần Thị Bình (TP Cán bộ)', 'binhtt@btctu.daklak.gov.vn', '0988777888', 3, 3, 'TRUONG_PHONG', 'ACTIVE'),
(4, 'tp_vanphong', 'password123', 'Đồng chí Lê Hoàng Nam (Chánh VP)', 'namlh@btctu.daklak.gov.vn', '0977666555', 5, 3, 'TRUONG_PHONG', 'ACTIVE'),
(5, 'cntt_user', 'password123', 'Đồng chí Phan Văn Cường (CV CNTT)', 'cuongpv@btctu.daklak.gov.vn', '0935222333', 5, 4, 'CHUYEN_VIEN', 'ACTIVE');

MERGE INTO kpi_criteria (id, code, name, group_type, max_score, scoring_guide, target_role) KEY(id) VALUES
(1, 'A1', 'Tư tưởng chính trị, đạo đức, kỷ cương công sở Đảng', 'A', 20.0, 'Chấp hành nghiêm kỷ luật kỷ cương hành chính và giờ giấc làm việc', 'ALL'),
(2, 'B1', 'Tiến độ và số lượng nhiệm vụ được phân công', 'B', 30.0, 'Tỷ lệ hoàn thành nhiệm vụ đúng hạn trong tháng', 'ALL'),
(3, 'B2', 'Chất lượng tham mưu văn bản chỉ đạo của Tỉnh ủy / Ban', 'B', 30.0, 'Đánh giá tỷ lệ văn bản đạt chất lượng ngay từ lần đầu', 'ALL'),
(4, 'C1', 'Sáng kiến, giải pháp cải cách hành chính và chuyển đổi số', 'C', 20.0, 'Ứng dụng CNTT rút ngắn thời gian xử lý công việc', 'ALL');

MERGE INTO tasks (id, title, description, assigned_to, assigned_by, department_id, task_type, complexity, speech_approved, start_date, due_date, progress, status, weight, evidence_text) KEY(id) VALUES
(1, 'Dự thảo Báo cáo công tác cán bộ quý IV/2026', 'Soạn thảo tờ trình và phụ lục báo cáo công tác cán bộ', 5, 4, 5, 'VAN_BAN', 'KHO', FALSE, '2026-10-01', '2026-10-25', 100, 'COMPLETED', 2.0, 'VB số 142-BC/BTCTU ngày 24/09/2026 trên Trục liên thông'),
(2, 'Chuẩn bị bài phát biểu của Lãnh đạo Ban tại Hội nghị', 'Dự thảo phát biểu chỉ đạo của Trưởng ban', 5, 4, 5, 'HOP', 'TRUNG_BINH', TRUE, '2026-10-05', '2026-10-20', 85, 'IN_PROGRESS', 1.5, 'Đã gửi bản thảo xin ý kiến Chánh Văn phòng');

MERGE INTO evaluations (id, user_id, department_id, period_type, period_value, self_score, manager_score, final_score, ranking, self_notes, manager_notes, leader_notes, status, evaluated_at, approved_by, approved_at) KEY(id) VALUES
(1, 5, 5, 'MONTH', 'Tháng 09/2026', 95.0, 96.0, 96.0, 'XUAT_SAC', 'Hoàn thành tốt nhiệm vụ', 'Chất lượng cao', 'Nhất trí xếp loại Xuất sắc', 'APPROVED', '2026-09-28 15:30:00', 2, '2026-09-30 09:00:00');

MERGE INTO department_evaluations (id, department_id, period_type, period_value, plan_score, quality_score, it_digital_score, discipline_score, avg_staff_score, ranking, leader_feedback, evaluated_by, evaluated_at) KEY(id) VALUES
(1, 5, 'MONTH', 'Tháng 09/2026', 28.0, 27.0, 14.0, 14.0, 9.5, 'XUAT_SAC', 'Văn phòng hoàn thành xuất sắc nhiệm vụ số hóa và tham mưu', 2, '2026-09-30 10:00:00');
